### ISSUE TITLE
comments on details page

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#102]
when you type "@" user names do not show up

**Comment by closurefyre** [comment]
@dustingtorres also, when you just try to add a comment with "@," you get redirected to 400 error page https://dev.surefyre.co/comments/post/ajax/

**Comment by closurefyre** [comment]
without "@"*** @dustingtorres

**Comment by dtorres-sf** [comment]
@closurefyre this should be fixed, please retest

**Comment by closurefyre** [comment]
fixed
