### ISSUE TITLE
Add product on lead page

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#11]
Browser: Chrome

Site: dev.surefyre.co

On testpad step: 0028 on Lead test script

Steps to reproduce:

select lead
select product and click "add product"
Expected result: should show product

Actual result:
![screen shot 2017-06-14 at 5 05 08 pm](https://user-images.githubusercontent.com/29260883/27159682-bc297600-5123-11e7-8c1b-c29e709a4486.png)

**Comment by dustingtorres** [comment]
Fixed, please verify

**Comment by closurefyre** [comment]
fixed
