### ISSUE TITLE
edit person on detail page

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#132]
when i clicked the pen for in the person section and then entered amount for mobile and income i got this

![screen shot 2018-03-06 at 8 09 18 pm](https://user-images.githubusercontent.com/29260883/37078515-691612a6-2194-11e8-85e9-20ade64af3ac.png)

**Comment by dtorres-sf** [comment]
@closurefyre fixed, please verify and close

**Comment by closurefyre** [comment]
fixed
