### ISSUE TITLE
verifying address on detail page

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#133]
does not show verified address when i typed in new address on detail page

https://dev.surefyre.co/account/5004712/68/

**Comment by closurefyre** [comment]
that also happens when i try to edit agent under polices on detail page

**Comment by dtorres-sf** [comment]
@closurefyre please verify and close

**Comment by closurefyre** [comment]
@dustingtorres fixed second part of ticket

**Comment by closurefyre** [comment]
fix* @dustingtorres

**Comment by dtorres-sf** [comment]
@closurefyre please close

**Comment by closurefyre** [comment]
fixed
