### ISSUE TITLE
Sending emails

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#15]
Browser: Chrome
Site: dev.surefyre.co
On testpad step: 0228

Steps to reproduce:
1. set up email template on admin site
2. select account
3. click "email" tab
4. select email template
5. send

Expected result:
able to send and receive email with correct information

Actual result:
not able to send email 

![screen shot 2017-06-16 at 4 38 43 pm](https://user-images.githubusercontent.com/29260883/27247978-cbb7f0f2-52b2-11e7-8882-d51cb83f23a6.png)

**Comment by closurefyre** [comment]
I did authorize google and tried again but got the same error message

**Comment by dustingtorres** [comment]
Can you please check the size of the image you attached.

**Comment by closurefyre** [comment]
Works now with a smaller attachment. Still a weird space with "hey" in
email but you looked at the source and cannot fix it

**Comment by closurefyre** [comment]
fixed
