### ISSUE TITLE
Edit lead on detail page

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#16]
Browser: Firefox
Site: dev.surefyre.co
On testpad step: 0038

Steps to reproduce:
1. click "create" on nav bar
2. fill out info (leave email and phone number empty) and save
3. on detail page, "click to edit" and add contact email and phone 
4. click "actions" then "edit"

Expected result:
After adding contact email and phone on detail page, new info should show on edit page when you click "actions"

Actual result:
Contact email and phone did not show after clicking "actions" then "edit." Will only show if you refresh after clicking to edit on detail page and before clicking "actions" 
![screen shot 2017-06-20 at 3 32 08 pm](https://user-images.githubusercontent.com/29260883/27358917-b212d158-55cd-11e7-85be-78f89ef6a0a2.png)

**Comment by dustingtorres** [comment]
This has been fixed. Please verify.

**Comment by closurefyre** [comment]
fixed
