### ISSUE TITLE
Email template error

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#17]
Browser: Firefox
Site: dev.surefyre.co
Testpad step: 0235

Steps to reproduce:
1. create template on admin site
2. go to dev site and select lead
3. click "email" tab and select template

Expected result:
After selecting email template, should add info to email body

Actual result:
Selected email template info does not show up in email body
![screen shot 2017-06-21 at 12 23 32 pm](https://user-images.githubusercontent.com/29260883/27402764-9e4bdd90-567c-11e7-9d83-c98bfba0c011.png)

**Comment by closurefyre** [comment]
related to #18

**Comment by dustingtorres** [comment]
This should be fixed, please retest.

**Comment by closurefyre** [comment]
When I selected one of the "Test Test" templates, the image didn't show up in email body
![screen shot 2017-06-28 at 12 57 14 pm](https://user-images.githubusercontent.com/29260883/27657422-755da69a-5c01-11e7-9aa6-b33540133ee0.png)

But when I went back to the admin site and reselected the same imagine for the "Test Test" template, then it will show up

**Comment by closurefyre** [comment]
fixed
