### ISSUE TITLE
Sending email error

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#18]
Browser: Firefox
Site: dev.surefyre.co
Testpad step: 0236

Steps to reproduce:
1. select account
2. click "email" tab
3. fill out email info
4. click "send"

Expected result:
Should be able send and receive email. "that's neat!" should pop up after clicking "send"

Actual result:
Email did not send and "that's neat!" did not pop up

**Comment by closurefyre** [comment]
retest on firefox and chrome

**Comment by closurefyre** [comment]
related to #17

**Comment by dustingtorres** [comment]
This should be fixed, please retest @closurefyre

**Comment by closurefyre** [comment]
fixed
