### ISSUE TITLE
Calendar 

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#23]
Browser: Chrome
Site: dev.surefyre.co

Steps to reproduce:
1. Click "Google Apps" on nav bar
2. select "calendar"
3. select time and day to add an event
4. click "cancel"

Expected result:
after clicking "cancel" it should close and take me back to the calendar page

Actual result:
Cannot cancel 
![screen shot 2017-06-29 at 1 42 27 pm](https://user-images.githubusercontent.com/29260883/27709559-6f075d9c-5cd1-11e7-8331-409d6f364a0a.png)

**Comment by closurefyre** [comment]
also happens with this pop up with the calendar. doesn't close when you click "close"

![screen shot 2017-06-29 at 2 23 15 pm](https://user-images.githubusercontent.com/29260883/27711038-a0f63f9e-5cd6-11e7-9101-f40ba974d4f2.png)

**Comment by closurefyre** [comment]
the "close" button still doesn't work and "cancel" is fixed @dustingtorres

**Comment by dustingtorres** [comment]
Should be fixed

**Comment by closurefyre** [comment]
fixed
