### ISSUE TITLE
Customer ID value increase/decrease button

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#28]
![screen shot 2017-07-01 at 11 51 03 am](https://user-images.githubusercontent.com/29260883/27764681-e725e0cc-5e53-11e7-8188-07ef3bf95a76.png)

If you push the customer id value button repeatedly, it stops working

**Comment by dustingtorres** [comment]
Fixed.

**Comment by closurefyre** [comment]
still kinda the same issue @dustingtorres

**Comment by dustingtorres** [comment]
Fixed now @closurefyre

**Comment by closurefyre** [comment]
fixed by deleting field completely
