### ISSUE TITLE
order date filter does not work

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#43]
![screen shot 2017-09-12 at 1 26 52 pm](https://user-images.githubusercontent.com/29260883/30348223-7d66867e-97c3-11e7-9790-476f25b0a893.png)

no orders show up if you select "this year" and the other options

**Comment by dustingtorres** [comment]
This is because the date filters on submitted date, not date that it was opened. I cleared up the wording and added a separate filter for created date.

**Comment by closurefyre** [comment]
fixed
