### ISSUE TITLE
save button does not work

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#49]
![screen shot 2017-09-12 at 3 20 35 pm](https://user-images.githubusercontent.com/29260883/30350975-02313eee-97ce-11e7-9b83-dff6be9e4079.png)

clicked "actions" then "edit" then entered new info, then clicked "save"

does not save and close

**Comment by dustingtorres** [comment]
@closurefyre can you provide more details, what did you change that made it not save? I am not able to reproduce this.

**Comment by closurefyre** [comment]
when you switch the primary, page needs to be refreshed before editing

**Comment by closurefyre** [comment]
@dustingtorres

**Comment by dustingtorres** [comment]
This is now fixed @closurefyre

**Comment by closurefyre** [comment]
fixed
