### ISSUE TITLE
Cannot save new lead/client

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#5]
Browser: safari

Site: dev.surefyre.co

Testpad step: 0003 in lead test script

Steps to reproduce:
1. log in to site
2. click "create" on nav bar
3. enter lead/client info
4. save

Expected result: adding and saving new lead/client information to dev site so it can been seen and searched

Actual result: doesn't do anything when I click the "save" button after filling out info

**Comment by dustingtorres** [comment]
This should be fixed.
