### ISSUE TITLE
Got "bad request" error when selecting location

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#51]
![screen shot 2017-09-12 at 5 35 40 pm](https://user-images.githubusercontent.com/29260883/30354337-e126c0a8-97e0-11e7-8f8b-e30a8a0e2029.png)

I tried selecting "SF" for location and it went to this page:
![screen shot 2017-09-12 at 5 34 56 pm](https://user-images.githubusercontent.com/29260883/30354347-f08d6f92-97e0-11e7-9e28-7fd625cb91b7.png)

**Comment by dustingtorres** [comment]
Fixedin next release

**Comment by closurefyre** [comment]
fixed
