### ISSUE TITLE
add "notes" section

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#52]
![screen shot 2017-09-12 at 5 44 34 pm](https://user-images.githubusercontent.com/29260883/30354551-133098de-97e2-11e7-9d7c-bddc558cab09.png)

**Comment by dustingtorres** [comment]
This is done in field display to show the data. I have added it, see here:
https://dev.surefyre.co/admin/field_display/fielddisplay/92/change/

**Comment by closurefyre** [comment]
fixed
