### ISSUE TITLE
pressing "enter" in "name" box causes error 500

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#53]
https://dev.surefyre.co/docs2/

![screen shot 2017-09-12 at 5 49 37 pm](https://user-images.githubusercontent.com/29260883/30354685-c32998d0-97e2-11e7-9418-d0edf51298a5.png)
 

And maybe move "save" button closer to "name" box

**Comment by dustingtorres** [comment]
Fixed in next release

**Comment by closurefyre** [comment]
![screen shot 2017-09-13 at 3 56 14 pm](https://user-images.githubusercontent.com/29260883/30404584-2cd9d65a-989c-11e7-9fbf-0de2f931c212.png)

move "save and review" button @dustingtorres

**Comment by dustingtorres** [comment]
Fixed

**Comment by closurefyre** [comment]
can you make the "doc select" box the same size as "name" and "product" @dustingtorres

**Comment by closurefyre** [comment]
fixed
