### ISSUE TITLE
add ability to delete document

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#56]
![screen shot 2017-09-12 at 6 29 01 pm](https://user-images.githubusercontent.com/29260883/30355436-5899b0a8-97e8-11e7-9fd6-1745b20e2a0b.png)

should add "delete document" like you have "delete attachment"

**Comment by closurefyre** [comment]
should be able to delete order too @dustingtorres 

![screen shot 2017-09-12 at 6 55 36 pm](https://user-images.githubusercontent.com/29260883/30356099-13dd1550-97ec-11e7-95e1-9a9af3759241.png)

**Comment by dustingtorres** [comment]
Adding delete back to orders, but it can only be done from the detail page.

**Comment by dustingtorres** [comment]
Documents, purposely don't have delete since they are so important for insurance (these are insurance docs).

**Comment by dustingtorres** [comment]
I can add a way to delete through admin if you need to delete for testing purposes.

**Comment by closurefyre** [comment]
fixed
