### ISSUE TITLE
cannot send

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#59]
https://dev.surefyre.co/redcloud/send/92/

![screen shot 2017-09-12 at 6 38 30 pm](https://user-images.githubusercontent.com/29260883/30355672-a98b138e-97e9-11e7-993a-d283362fc683.png)

clicked the "send" icon and i got the error 500 page

**Comment by closurefyre** [comment]
also, the view icon takes you to the report builder page. not sure if "view" is the write word, maybe "report" but im not sure what the purpose of view is

**Comment by closurefyre** [comment]
also, the delete icon is too easy to delete too

**Comment by closurefyre** [comment]
@dustingtorres

**Comment by dustingtorres** [comment]
This is not intended to work on dev site. I have removed it from dev site.
