### ISSUE TITLE
upload file on email

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#64]
![screen shot 2017-09-19 at 3 07 03 pm](https://user-images.githubusercontent.com/29260883/30617751-5e63ab56-9d4c-11e7-9da3-8527644e1d5b.png)

uploaded file appears on the top of the email body which is weird, should be at the bottom unless you wanted it there

**Comment by dtorres-sf** [comment]
It goes wherever the cursor goes. It is used as links in the email so you can do something like:

Check out this [file](http://www.pdf995.com/samples/pdf.pdf) that I just sent
