### ISSUE TITLE
Dashboard table

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#7]
Browser: Safari
Site: dev.surefyre.co

when I maximize the window, the dashboard table is cut off on the right side

**Comment by closurefyre** [comment]
![screen shot 2017-06-07 at 4 02 34 pm](https://user-images.githubusercontent.com/29260883/26905191-c96ec740-4b9a-11e7-8df2-8ab28e46f323.png)

**Comment by dustingtorres** [comment]
This is due to lack of scroll bars, need to look at why tablesorter does not show scrollbars on safari.

**Comment by closurefyre** [comment]
need to turn on scroll bar on mac preferences for it to show up, not bug
