### ISSUE TITLE
google apps>calendar

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#71]
![screen shot 2017-09-27 at 4 31 25 pm](https://user-images.githubusercontent.com/29260883/30942725-71e3057c-a3a1-11e7-8f02-6dd46941a381.png)

**Comment by dustingtorres** [comment]
Fixed

**Comment by dustingtorres** [comment]
Fixed

**Comment by closurefyre** [comment]
fixed
