### ISSUE TITLE
not able to edit policies

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#86]
![screen shot 2017-11-07 at 5 25 28 pm](https://user-images.githubusercontent.com/29260883/32526975-f784fd98-c3e0-11e7-9eae-140ce7e83bdb.png)

I cannot edit when I click "catherine lo" and can't edit anything else in that section

**Comment by dustingtorres** [comment]
Good catch, this caused other issues that should now be resolved to.
