### ISSUE TITLE
Add product on lead page

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#9]
Browser: Firefox

Site: dev.surefyre.co

On testpad step: 0028 on Lead test script 

Steps to reproduce:
1. select lead
2. select product and click "add product"

Expected result: should show product

Actual result:
![screen shot 2017-06-08 at 4 55 28 pm](https://user-images.githubusercontent.com/29260883/26955499-f1399c06-4c6b-11e7-9416-9869644dd8fd.png)

**Comment by dustingtorres** [comment]
Related to #11

**Comment by dustingtorres** [comment]
I think this is fixed, please verify @closurefyre

**Comment by closurefyre** [comment]
I clicked "add product" without selecting product, then got "this field is required." So then I selected  a product and clicked "add product" but would add two products instead of one

**Comment by dustingtorres** [comment]
This should be fixed. Please retest

**Comment by closurefyre** [comment]
fixed
