### ISSUE TITLE
make "save and review" button more visable

### ISSUE THREAD

**Issue by closurefyre** [dustingtorres/surefyre-tickets#96]
![screen shot 2017-11-13 at 4 28 49 pm](https://user-images.githubusercontent.com/29260883/32756606-d266c498-c88f-11e7-8f0c-2b362af9596d.png)

**Comment by dustingtorres** [comment]
I can't reproduce this, what browser are you using? Here is what it looks like for me:
![image](https://user-images.githubusercontent.com/10240990/32758393-07ea6bac-c899-11e7-8b33-abf7605ec330.png)

**Comment by closurefyre** [comment]
fixed
